boot.o: boot.S multiboot.h x86_desc.h types.h
system_call_linkage.o: system_call_linkage.S system_call_linkage.h \
  types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception_handler.o: exception_handler.c exception_handler.h lib.h \
  types.h x86_desc.h system_calls.h files.h keyboard.h i8259.h rtc.h \
  ../syscalls/ece391syscall.h ../syscalls/../student-distrib/types.h \
  paging.h
files.o: files.c files.h types.h lib.h keyboard.h i8259.h rtc.h \
  ../syscalls/ece391syscall.h ../syscalls/../student-distrib/types.h \
  x86_desc.h system_calls.h paging.h exception_handler.h
i8259.o: i8259.c i8259.h types.h lib.h
init_idt.o: init_idt.c init_idt.h x86_desc.h types.h lib.h \
  exception_handler.h system_calls.h files.h keyboard.h i8259.h rtc.h \
  ../syscalls/ece391syscall.h ../syscalls/../student-distrib/types.h \
  paging.h system_call_linkage.h scheduling.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  paging.h init_idt.h exception_handler.h system_calls.h files.h \
  keyboard.h rtc.h ../syscalls/ece391syscall.h \
  ../syscalls/../student-distrib/types.h system_call_linkage.h \
  scheduling.h
keyboard.o: keyboard.c keyboard.h types.h i8259.h lib.h rtc.h \
  ../syscalls/ece391syscall.h ../syscalls/../student-distrib/types.h \
  files.h x86_desc.h system_calls.h paging.h exception_handler.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h keyboard.h files.h x86_desc.h \
  system_calls.h paging.h exception_handler.h ../syscalls/ece391syscall.h \
  ../syscalls/../student-distrib/types.h
scheduling.o: scheduling.c scheduling.h types.h i8259.h lib.h keyboard.h \
  rtc.h ../syscalls/ece391syscall.h \
  ../syscalls/../student-distrib/types.h files.h x86_desc.h \
  system_calls.h paging.h exception_handler.h
system_calls.o: system_calls.c system_calls.h types.h lib.h files.h \
  keyboard.h i8259.h rtc.h ../syscalls/ece391syscall.h \
  ../syscalls/../student-distrib/types.h x86_desc.h paging.h \
  exception_handler.h
terminal_handler.o: terminal_handler.c
